dataset: cifar100
early_stop_patience: 5
epochs: 50
forget_classes:
- 0
- 1
layer_wise: false
method: random_pruning
model_type: resnet18
optimizer: adamw
optimizer_kwargs:
  lr: 0.01
  weight_decay: 0.01
save_dir: ../results
seed: 0
sparsity: 0.1
